import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Civonex — Educate. Empower. Engage.",
  description:
    "Civonex is a digital-first platform focused on education, civic awareness, and empowering institutions through technology.",
  keywords: [
    "civic sense",
    "education platform",
    "student awareness",
    "digital society",
    "Civonex",
  ],
};


import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
